[build]
  command = "yarn build"
  publish = "build/"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  # https://community.netlify.com/t/support-guide-using-private-npm-modules-on-netlify/795/65
  YARN_VERSION = "1.22.10"

[context.production.environment]

[context.deploy-preview]
  ignore = "git diff --quiet HEAD^ HEAD src/ index.html package.json yarn.lock"
